---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: workshop-main
    provider: jkube
    version: 1.0.0-SNAPSHOT
    group: com.workshop.main
  name: service-config-map
data:
  application.properties: |-
    resteasy.jaxrs.defaultPath:/api
    common.uri=services.common.svc.cluster.local:8080
    test=openshift
